import img_model

def section_header(title = 'Title', portfolio = 'Portfolio'):
	s = ''
	s += '<!DOCTYPE html>\n'
	s += '<html>\n'
	s += '<head>\n'
	s += '<meta name="viewport" content="width=device-width, initial-scale=1">\n'
	s += '<style>\n'
	s += '* {\n'
	s += '  box-sizing: border-box;\n'
	s += '}\n'
	s += '\n'
	s += 'body {\n'
	s += '  background-color: #f1f1f1;\n'
	s += '  padding: 20px;\n'
	s += '  font-family: Arial;\n'
	s += '}\n'
	s += '\n'
	s += '/* Center website */\n'
	s += '.main {\n'
	s += '  max-width: 1000px;\n'
	s += '  margin: auto;\n'
	s += '}\n'
	s += '\n'
	s += 'h1 {\n'
	s += '  font-size: 50px;\n'
	s += '  word-break: break-all;\n'
	s += '}\n'
	s += '\n'
	s += '.row {\n'
	s += '  margin: 10px -16px;\n'
	s += '}\n'
	s += '\n'
	s += '/* Add padding BETWEEN each column */\n'
	s += '.row,\n'
	s += '.row > .column {\n'
	s += '  padding: 8px;\n'
	s += '}\n'
	s += '\n'
	s += '/* Create equal columns that float next to each other */\n'
	s += '.column {\n'
	s += '  float: left;\n'
	s += '  width: 25.00%;\n'
	s += '  display: none; /* Hide all elements by default */\n'
	s += '}\n'
	s += '\n'
	s += '/* Clear floats after rows */ \n'
	s += '.row:after {\n'
	s += '  content: "";\n'
	s += '  display: table;\n'
	s += '  clear: both;\n'
	s += '}\n'
	s += '\n'
	s += '/* Content */\n'
	s += '.content {\n'
	s += '  border: 1px;\n'
	s += '  background-color: white;\n'
	s += '  padding: 10px;\n'
	s += '}\n'
	s += '\n'
	s += '/* The "show" class is added to the filtered elements */\n'
	s += '.show {\n'
	s += '  display: block;\n'
	s += '}\n'
	s += '\n'
	s += '/* Style the buttons */\n'
	s += '.btn {\n'
	s += '  border: none;\n'
	s += '  outline: none;\n'
	s += '  padding: 12px 16px;\n'
	s += '  background-color: white;\n'
	s += '  cursor: pointer;\n'
	s += '}\n'
	s += '\n'
	s += '.btn:hover {\n'
	s += '  background-color: #ddd;\n'
	s += '}\n'
	s += '\n'
	s += '.btn.active {\n'
	s += '  background-color: #666;\n'
	s += '  color: white;\n'
	s += '}\n'
	s += '</style>\n'
	s += '</head>\n'
	s += '<body>\n'
	s += '\n'
	s += '<!-- MAIN (Center website) -->\n'
	s += '<div class="main">\n'
	s += '\n'
	s += '<h1>' + title + '</h1>\n'
	s += '<hr>\n'
	s += '\n'
	s += '<h2>' + portfolio + '</h2>\n'
	return s

def section_buttons(gallery):
	#print(gallery)
	topics = {}
	for i, (k, im) in enumerate(sorted(gallery.items())):
		topics[im.type.replace(' ', '_')] = im.type
	s = ''
	#print(topics)
	s += '<div id="myBtnContainer">\n'
	for i, (k, v) in enumerate(sorted(topics.items())):
		if (i == 0):
			s += '  <button class="btn active" onclick="filterSelection(\'all\')"> Show All</button>\n'
		else:
			s += '  <button class="btn" onclick="filterSelection(\'' + k + '\')"> ' + v + '</button>\n'
	s += '</div>\n'
	return s

def section_grid(gallery):
	s = ''
	s += '<!-- Portfolio Gallery Grid -->\n'
	s += '<div class="row">\n'
	for i, (k, im) in enumerate(sorted(gallery.items())):
		s += '  <div class="column ' + im.type.replace(' ', '_') + '">\n'
		s += '    <div class="content">\n'
		s += '      <a href="' + im.filename + '" target="_blank">\n'
		s += '         <img src="' + im.filename + '" alt="' + im.v['LABEL'] + '" style="width:100%">\n'
		s += '      </a>\n'
		s += '      <p style="font-size:14px;">' + im.v['LABEL'] + '</p>\n'
		s += '      <p style="font-size:10px;">' + im.p + '</p>\n'
		s += '    </div>\n'
		s += '  </div>\n'
	s += '<!-- END GRID -->\n'
	s += '</div>\n'
	return s

def section_footer():
	s = ''
	s += '<!-- END MAIN -->\n'
	s += '</div>\n'
	s += '\n'
	s += '<script>\n'
	s += 'filterSelection("all")\n'
	s += 'function filterSelection(c) {\n'
	s += '  var x, i;\n'
	s += '  x = document.getElementsByClassName("column");\n'
	s += '  if (c == "all") c = "";\n'
	s += '  for (i = 0; i < x.length; i++) {\n'
	s += '    w3RemoveClass(x[i], "show");\n'
	s += '    if (x[i].className.indexOf(c) > -1) w3AddClass(x[i], "show");\n'
	s += '  }\n'
	s += '}\n'
	s += '\n'
	s += 'function w3AddClass(element, name) {\n'
	s += '  var i, arr1, arr2;\n'
	s += '  arr1 = element.className.split(" ");\n'
	s += '  arr2 = name.split(" ");\n'
	s += '  for (i = 0; i < arr2.length; i++) {\n'
	s += '    if (arr1.indexOf(arr2[i]) == -1) {element.className += " " + arr2[i];}\n'
	s += '  }\n'
	s += '}\n'
	s += '\n'
	s += 'function w3RemoveClass(element, name) {\n'
	s += '  var i, arr1, arr2;\n'
	s += '  arr1 = element.className.split(" ");\n'
	s += '  arr2 = name.split(" ");\n'
	s += '  for (i = 0; i < arr2.length; i++) {\n'
	s += '    while (arr1.indexOf(arr2[i]) > -1) {\n'
	s += '      arr1.splice(arr1.indexOf(arr2[i]), 1);\n'
	s += '    }\n'
	s += '  }\n'
	s += '  element.className = arr1.join(" ");\n'
	s += '}\n'
	s += '\n'
	s += '// Add active class to the current button (highlight it)\n'
	s += 'var btnContainer = document.getElementById("myBtnContainer");\n'
	s += 'var btns = btnContainer.getElementsByClassName("btn");\n'
	s += 'for (var i = 0; i < btns.length; i++) {\n'
	s += '  btns[i].addEventListener("click", function(){\n'
	s += '    var current = document.getElementsByClassName("active");\n'
	s += '    current[0].className = current[0].className.replace(" active", "");\n'
	s += '    this.className += " active";\n'
	s += '  });\n'
	s += '}\n'
	s += '</script>\n'
	s += '\n'
	s += '</body>\n'
	s += '</html>\n'
	return s